package com.intuit.craft.entities;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;
import java.util.Map;

@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "BusinessProfile")
public class BusinessProfile {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private String companyName;
    @DynamoDBAttribute
    private String LegalName;
    @DynamoDBAttribute
    private Address businessAddress;
    @DynamoDBAttribute
    private Address legalAddress;
    @DynamoDBAttribute
    private String taxIdentifier;
    @DynamoDBAttribute
    private String email;
    @DynamoDBAttribute
    private String website;
    @DynamoDBAttribute
    private List<Product> products;
}
